version: "3.8"

services:
  mongodb:
    image: mongo:5.0.6-focal
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
