version: "3.8"

services:
  mariadb:
    image: mysql:8.0.29-oracle
    restart: on-failure
    environment:
      - TZ=UTC
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
